### ISSUE TITLE
Compabiliteit tussen kalenderformaat event-ld van UiTdatabank en Activiteit van Oslo

### ISSUE THREAD

**Issue by svenhoutmeyers** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#1]
Op zich beschikken we denken we nog niet over zoveel informatie hoe kalenderinformatie in Oslo wordt bewaard, maar we maken ons wel een beetje zorgen over de compabiliteit tussen de twee verschillende formaten.

**Wat we weten uit Oslo?**

<img width="244" alt="Screenshot 2022-03-21 at 16 35 21" src="https://user-images.githubusercontent.com/897699/159297475-a3645b49-5801-4f1f-8525-976c91d9a9de.png">

- een activiteit kan een sub- of superactiviteit hebben 
- een activiteit heeft een property **tijd** TM_object

**Waar zien we wel enkele issues?**

In UiTdatabank kan een **event** vier verschillende calendarTypes hebben:

- single
- multiple
- periodic
- permanent

Maar een **place** (Locatie in Oslo) kan er ook twee hebben:

- periodic
- permanent

Hier wat meer info over deze 4 verschillende types.

**single**
Has startDate, endDate and 1 subEvent. The startDate and endDate of the subEvent is the same as the one of the top event.
Both the top event and the subEvent have a status and and a bookingAvailability
Applicable on: events
Example https://io.uitdatabank.be/event/16045ef7-5370-4059-872d-a1c21094d2c4

```
calendarType: "single",
startDate: "2022-03-22T19:30:00+01:00",
endDate: "2022-03-22T22:00:00+01:00",
status: {
type: "Available"
},
bookingAvailability: {
type: "Available"
},
subEvent: [
{
id: 0,
status: {
type: "Available"
},
bookingAvailability: {
type: "Available"
},
startDate: "2022-03-22T19:30:00+01:00",
endDate: "2022-03-22T22:00:00+01:00",
@type: "Event"
}
],
```

**multiple**
Has startDate, endDate and 2 ore more subEvents.
Both the top event and the subEvents have a status and and a bookingAvailability. The status and bookingAvailability on top event level is derived from the statuses on subEvent level
Applicable on: events
Example https://io.uitdatabank.be/event/7e5739fb-c3ac-4b36-84e9-d6b9cbdf3f9e

```
calendarType: "multiple",
startDate: "2022-04-21T10:00:00+02:00",
endDate: "2022-04-28T12:30:00+02:00",
status: {
type: "Available"
},
bookingAvailability: {
type: "Available"
},
subEvent: [
{
id: 0,
status: {
type: "Available"
},
bookingAvailability: {
type: "Available"
},
startDate: "2022-04-21T10:00:00+02:00",
endDate: "2022-04-21T12:30:00+02:00",
@type: "Event"
},
{
id: 1,
status: {
type: "Available"
},
bookingAvailability: {
type: "Available"
},
startDate: "2022-04-28T10:00:00+02:00",
endDate: "2022-04-28T12:30:00+02:00",
@type: "Event"
}
],
```

**periodic**
Has a startDate, endDate and sometimes openingHours
The event has a status and a bookingAvailability. The bookingAvailability is always “Available” (atm)
Applicable on: events, places
Example https://io.uitdatabank.be/event/eab93223-0cbe-497f-b037-da3f46571592

```
calendarType: "periodic",
startDate: "2022-07-11T00:00:00+02:00",
endDate: "2022-07-15T00:00:00+02:00",
status: {
type: "Available"
},
bookingAvailability: {
type: "Available"
},
openingHours: [
{
opens: "09:00",
closes: "16:00",
dayOfWeek: [
"monday",
"tuesday",
"wednesday",
"thursday",
"friday"
]
}
],
```

**permanent**
Has no startDate or endDa but can contain openingHours
The event has a status and a bookingAvailability. The bookingAvailability is always “Available” (atm)
Applicable on: events, places
Example https://io.uitdatabank.be/event/725BAB6A-AAC5-10AC-42348AE4E9FDBC8C

```
calendarType: "permanent",
openingHours: [
{
opens: "12:00",
closes: "19:00",
dayOfWeek: [
"monday"
]
},
{
opens: "08:00",
closes: "12:00",
dayOfWeek: [
"tuesday",
"wednesday",
"thursday",
"friday",
"saturday",
"sunday"
]
}
]
```
We zien vooral momenteel nog niet hoe periodic en permanent events in het Oslo-datamodel zullen worden gerepresenteerd. Een lijst van allemaal apart events (via sub- of super) kan wel eens heel complex worden (en niet mogelijk voor permanent). Ook bij multiple gaat het veel moeilijker zijn voor integratoren als de subevents in aparte events zitten (tov. zoals in de UiTdatabank waar het een property is).

**Comment by jitsedc** [comment]
Opgelost door de toevoeging van Ruimtetijd, geleend uit CIDOC-CRM. Voor meer informatie rond de toepassing hiervan zie het verslag van de bijkomende 6de werkgroep.
