### ISSUE TITLE
De linken naar cultureel erfgoed ding kunnen niet getypeerd worden

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#10]
Nochtans is het belangrijk om aan te kunnen geven hoe zo een cultureel erfgoed ding wordt gebruikt. Is het louter een inspiratie, wordt er een fragment van gebruikt, is het een herwerking, ...

**Comment by jitsedc** [comment]
Op zich kan veel van de mogelijke typering afgeleid worden indien er vanuit `Ding` verder wordt gespecialiseerd naar de verschillende klassen uit OSLO-Cultureel Erfgoed. Zo is er bij het tonen van een fragment bijvoorbeeld sprake van OSLO-Cultureel Erfgoed::Opname, ter inspiratie is er dan sprake van OSLO-Cultureel Erfgoed::ConceptueelDing, etc. 

Te bespreken maar als final option zou er bijvoorbeeld attribuut `toepassing` od. kunnen worden toegevoegd indien verdere specialisering vanuit `Ding` niet voldoende is om de use cases te realiseren.

**Comment by ruettet** [comment]
Hey, kan je links geven naar die oslo cultureel erfgoed : opname, conceptueelding standaarden? Dan kan ik eens zien of dat zou kunnen werken.

**Comment by jitsedc** [comment]
Zeer zeker:

-[`Cultureel Erfgoed::Opname`](https://data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-object#Opname)
-[`Cultureel Erfgoed::ConceptueelDing`](https://data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-object#Conceptueel%20Ding)

**Comment by ruettet** [comment]
ik zie het niet meteen, Jitse? De typering zit dan in de subtyping? Ik vrees dat dat niet rijk genoeg is om kunstenerfgoed te beschrijven. Hoe geef je aan dat een podiumproductie in seizoen 2020-2021 een herneming is van dezelfde productie in 2010-2011, maar dan met een hele andere cast van uitvoerders?

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
