### ISSUE TITLE
Rollen en types ook vrije tekst

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#11]
Het is natuurlijk belangrijk dat rollen en types gestructureerd worden ingevoerd, maar het is soms ook belangrijk om daar bovenop nog in vrije tekst een rol of type verder te kunnen beschrijven. Bv. in theater is het soms de gewoonte om "van en met" te schrijven als rol, maar eigenlijk is de rol die wordt opgenomen "acteur". Het is belangrijk dat de standaard ruimte laat hiervoor.

**Comment by jitsedc** [comment]
Technisch kan er bij de enumeratie een free text enumeratiewaarde voorzien worden. Dit maakt de data wel minder slim en ondergraaft uitwisseling tot een zekere hoogte.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
