### ISSUE TITLE
Media? En Auteursrecht?

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#12]
Het model lijkt geen ruimte te maken om media mee uit te wisselen, bv. een foto (of een link naar een locatie van een foto). Als dat nog kan, is er ook ruimte nodig om auteursrechtelijke informatie in op te slaan.

**Comment by zvdh** [comment]
Ik probeer even mee te denken: is dat op niveau van de `Activiteit` of op niveau van `Promotie`?
Heel goede opmerking om informatie ivm auteursrecht op te nemen.

**Comment by jitsedc** [comment]
Het uitwisselen van media is voorzien aan de hand van `Document`. Dit moet echter ook nog verder uitgewerkt worden voor OSLO-Generiek. We kunnen wel een `uri` attribuut voorzien bij `Document` waardoor deze functionaliteit toch al (gedeeltelijk) mogelijk wordt. 

Auteursrecht is relevante en interessante informatie om mee te nemen maar dit heeft een apart traject nodig om tot een standaard die de use cases van DDT overstijgt. We houden dit daarom out of scope voor dit specifiek traject.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
