### ISSUE TITLE
Triggers bij Activiteiten

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#13]
Het wordt in de kunstensector duidelijker dat sommige kunstactiviteiten gepaard moeten gaan met triggerwarnings (bv. stroboscopisch licht, heftige beelden, taal, ...) Er is geen ruimte in het model om zulke triggers te modelleren?

**Comment by jitsedc** [comment]
We stellen voor om `trigger` toe te voegen als nieuw attribuut gekoppeld aan `Activiteit` met een `skos:Concept` als waarde. Moet dit ook voorzien worden op niveau van Ding?

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
