### ISSUE TITLE
url? url type?

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#14]
Het lijkt me logisch dat bij participanten, uitvoerders, aanbieders en activiteiten minstens één URL geplaatst kan worden, en dat er een type aan die URL kan toegevoegd worden (bv. "meer info" of "trailer" of ...) Dat lijkt nu niet voorzien te zijn?

**Comment by jitsedc** [comment]
Wij zien dit momenteel vallen onder `ContactInfo` uit OSLO-Generiek. Is dit voor jullie voldoende? 

![image](https://user-images.githubusercontent.com/93584054/188752087-d400d331-67bf-4031-8d8d-1546837701c4.png)

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
