### ISSUE TITLE
Waardelijsten

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#15]
De waardelijsten lijken me nog niet in orde. Ik bekijk die wat te linken zijn aan het aanbod:
- activiteittype: verwart nog steeds een "supercategorie" (bv. kijkenEnLuisteren) met een "subcategorie" (bv. concert, dansvoorstelling)
- thematype: dit verwart genres (jazz) en onderwerpen (feminisme) >>> moeten er genres benoemd worden in een waardenlijst?
- disciplinetypes: dit verwart disciplines (fotografie), sectoren (erfgoed) en aanbieders (archieven)
- activiteitfunctietype: geen idee wat er hier mee bedoeld wordt, ik zie geen lijn in de opsomming?
- objecttype: stream (van muziek? van video?) en podcast zijn digitaal, boek is fysiek, film is via een scherm, muziek is een discipline, ...
- aanbiedertype: programmatoren en curatoren doen een artistieke keuze, zijn ze daarom niet eerder uitvoerders? het lijkt me hier logischer om concertzalen, concertorganisatoren, promotiegaleries, tentoonstellingsruimtes, kunstbeurzen, cultuurcentra, theaters, ... op te sommen?
- samenwerkingtype: er ontbreken zaken, bv. "representatie"
- uitvoerderroltype: ook hier ontbreekt weer vanalles, acteurs, regiseur, scenografie, kostuumontwerp, pyro, bassist, curator, ...
- locatietype: is dit niet dan net het medium?

Volgens mij ontbreken nog deze waardelijsten:
- genres
- aanbiederroltype
- uitvoerdertype

En zoals elders gezegd: deze gestructureerde waardes moeten ook altijd gepaard kunnen gaan met vrije tekst.

**Comment by zvdh** [comment]
Wat ons betreft is hier inderdaad nog werk aan.

- `Activiteittype` is puur de lijst van de UiT-databank. Deze combineert zoals Tom opmerkte een overkoepelende categorie met een subcategorie. Voor het sociaal-cultureel werk is deze lijst in ieder geval lang niet toereikend om alle activiteiten in onder te brengen: een uitstap van een Okra-afdeling of vorming van Wisper lukt nog wel, maar acties van Hart boven hard of [Autodelen.net](http://autodelen.net/), campagnes van Bond zonder Naam, inhoudelijke dossiers van Kif Kif of beleidsbeïnvloeding door Çavaria of De Transformisten zijn al heel wat moeilijker te plaatsen.

  Vanuit Socius kunnen we desgewenst een poging doen om een meer sluitende typologie op te stellen, op basis van het onderzoek naar de beleidsplannen van de erkende organisaties in het sociaal-cultureel werk (nu in afrondende fase) en het onderzoek naar de voortgangsrapportage (in 2023). 
- `ThemaType` lijkt sowieso een uitbreidbare lijst, meer iets als tags dan als categorieën.
- `DisciplineType` is ook zo’n rare lijst. Geldt zowel voor deze als voor `ThemaType` dat deze niet verplicht zijn om aan te duiden?
- `AciviteitFunctieType` lijkt ons een goede plek om onder meer de sociaal-culturele functies op te nemen: leerfunctie, gemeenschapsvormende functie, cultuurfunctie en maatschappelijke bewegingsfunctie. Met name als het om deze functies gaat is het aangewezen om het mogelijk te maken om meerdere functies te kunnen selecteren.
- `UitvoerderRolType` moet inderdaad nog verder uitgebreid worden. Vanuit het sociaal-cultureel werk denken we dan bijvoorbeeld aan organisatie, freelancer, vrijwilliger, enzovoorts.
- `DoelgroepType` is nergens gedefinieerd en 'zweeft' dus los in het schema. Klopt allicht ook niet.
- `ParticipantType` geeft vier opties, maar alle verder gekoppelde zaken onder `SociodemografischKenmerk` verwijzen enkel naar een natuurlijk persoon (of beter gezegd, natuurlijkPersoon). Worden er andere velden opgenomen bij rechtspersoon, feitelijkeVereniging en publiekeOrganisatie? Blijft dit dan leeg?
- `PrijsCategorieType` is wel zeer beperkt: wat met kansengroepen, vrije bijdrage, …

**Comment by jitsedc** [comment]
- `skos:Concept `dat gebruikt wordt om de waardelijsten te modelleren behoort tot `skos:ConceptScheme`. Een mix van zelfde of meerdere lijsten kan gebruikt worden. Zo kan een supercategorie gecombineerd worden met een subcategorie zoals geïllustreerd in de voorbeeldenumeratie. We kunnen dit wel opsplitsen als dit tot verwarring leidt. 

- De concrete invulling van de verschillende types die hier worden aangehaald zullen we nog verder verfijnen zodat er geen semantische onduidelijkheid is. 

- Het is dus m.a.w. beter om meerdere lijsten te maken, deze goed uit te werken, bv. typering volgens genre, type, thema, etc. Dit zit echter niet in scope van het traject maar is wel mogelijk met een uitbreiding om specifiek tot afspraken te komen rond codelijsten. 

- `ActiviteitFunctietype` heeft wel degelijk waarden. Is dit voor @ruettet niet zichtbaar?
![image](https://user-images.githubusercontent.com/93584054/188749722-f0892119-a4e5-4595-bcb1-8fbfb2d9595c.png)

- Rond `uitvoerderroltype`: we kunnen deze zaken toevoegen maar het is niet de intentie om tot volledige lijsten te komen in deze enumeraties. 

- Gezien er gewerkt wordt met 'skos:concept' is er de mogelijkheid om vrije invulling te geven. Dit is echter niet ideaal. 

- Kardinaliteit van `DisciplineType` & `ThemaType` staat op 0..* het is dus niet verplicht om dit mee te geven. 

- `ActiviteitFunctieType` werd in eerste instantie toegevoegd om te voldoen aan rapporteringstandaarden van het ESS (Europees Statistisch Bureau). Deze kan wel uitgebreid worden indien nodig. 

- `publiek` werd toegevoegd als attribuut en gekoppeld aan de zwevende enumeratie. De relatie tussen `Activiteit` en `ParticipantProfiel` werd hernoemd naar `gerichtProfiel`

- `ParticipantType` werd voorzien zodat niet per se alle attribuering die komt kijken bij `OSLO-Persoon` of `OSLO-Organisatie` en verdere specialisering moet worden ingevuld. Indien deze informatie toch beschikbaar is, is het wenselijker om dit wel aan te vullen in plaats van `type` bij `AlgemeenParticipantKenmerk `in te vullen. 

- Hebben jullie concrete andere voorbeelden voor andere waarden voor `PrijsCategorieType`?

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
