### ISSUE TITLE
Deelname aan activiteiten

### ISSUE THREAD

**Issue by zvdh** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#16]
Deelname veronderstelt ook een tijdstip, gedefinieerd in `Periode` (wat ik niet terugvond). Echter is een activiteit zoals we dit binnen het sociaal-cultureel werk kennen niet steeds te koppelen aan een vast tijdstip: die dag van dat uur tot dat uur. Het kan ook om deelname aan een actie gaan, die over een langere periode loopt. Behoort dit dan ook tot de mogelijkheden?

`DeelnameType`: zie issue #6.

Interpreteer ik het juist dat, wanneer iemand deelneemt aan een activiteit zonder kostprijs (bijvoorbeeld een ledenactiviteit van een vereniging), deze volgens het huidige schema ook de stappen van `Transactie` naar `Ticket` moet doorlopen om daar bij `Tickettype` het type ‘registratie’ te kiezen? Dit lijkt me in het huidige schema de enige mogelijke weg, tenzij deelname zonder `Transactie` en `Ticket` ook mogelijk is.

Heeft de flow van `Participant` > `Deelname` > `Transactie` > `Ticket` trouwens een dwingend karakter? Stel dat ik met mijn gezin of met vrienden naar een voorstelling wil en daar 4 of 8 tickets voor boek. Moeten deze dan allemaal op naam geregistreerd worden om het systeem sluitend te houden?

**Comment by jitsedc** [comment]
`Periode` is in het herwerkte diagram aanwezig en wordt geleend van OSLO-Generiek. Langere periodes zijn zeker mogelijk op deze manier. 

![image](https://user-images.githubusercontent.com/93584054/188748770-97583570-503f-4324-b7a3-ccf396680a67.png)

De kardinaliteit van de relaties tussen `Deelname` en `Transactie `is 0..*. Het is dus mogelijk om een `Deelname` te hebben zonder dat de stappen richting `Ticket` moeten doorlopen worden. 

Bij het concrete voorbeeld: de stappen moeten gevolgd worden maar deze moeten niet op naam worden geregistreerd. Op zich is `Participant` gewoon een specialisering van `Agent` waarbij geen additionele informatie nodig is. Bijkomende informatie kan maar moet dus m.a.w. niet gegeven worden om het systeem sluitende te houden. Er worden dan gewoon "dummy" participanten aangemaakt waarover verder niets geweten is.
