### ISSUE TITLE
Cultuuraanbod-Toegangsrecht-Toegangsaanvraag-Toegangsactiviteit-Invulling

### ISSUE THREAD

**Issue by jodelaure** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#17]
Betreft kandidaat vocabularium op https://data.vlaanderen.be/ns/cultuurparticipatie

De toegang tot een cultuuraanbod, om de cultuurparticipatie te realiseren, is vaak afhankelijk van toegangsvoorwaarden. 
Het lijkt ons nuttig om hiervoor een anker in het datamodel te voorzien.

Nu is wel 'prijsCategorie' voorzien in het model maar prijs is een attribuut van het generiekere toegangsrecht.  Naast prijs zijn er immers andere modaliteiten van toegangsvoorwaarden denkbaar. 

Heel concreet bijvoorbeeld is het aanbod van de Luisterpunt bibliotheek gratis voor mensen met een visuele beperking.  De leden van luisterpunt krijgen een bij wet bemiddelde toegang die hen vrijstelt van een retributie aan de rechthebbenden van de aangeboden cultuurproducten. 

Andere gerelateerde uses cases zijn onderanderen: 
- Toegang tot de stedelijke musea voor de inwoners van een gemeente/stad is gratis.
- Toegang tot bepaalde bibliotheekdiensten is leeftijdsafhankelijk. Voorheen was het wettelijk bepaald dat toegang tot 18 jaar gratis moet zijn.  Vaak is dat nog bij de concrete gemeentelijke uitbating.
- Toegang tot een tentoonstelling voor leden van een organisatie is gratis.
- Minimumleeftijd voor diensten via sociale media is 13j.
- Toegang via Museumpas.
- Korting voor <25 >65 jaar als dan niet met een tijdsvenster.
- Toegang voor bepaalde categorieën voorbehouden voor bepaalde groepen in bepaalde tijdsvensters (woensdagnamiddag enkel voor kinderen).

Voor een voorbeeld-modellering van toegang langs de concepten van een aanbod, een toegangsaanvraag, een toegangsrecht en een toegangsactiviteit zie: https://luisterpunt.data.gift/application-profiles/loan/

We vermoeden ook dat 1 cultuurproduct niet hoeft gelimiteerd te worden tot 1 manier van 'consumptie', m.a.w. er kunnen verschillende (vaak digitale) manieren zijn waarop men de cultuurparticipatie opneemt.  Het lijkt ons daarom nuttig dat het datamodel ook hier voorziet in een anker om de modaliteiten van 'instantiatie', 'consumptie' of 'levering' te bepalen. 

Use cases waar we aan denken:
- Het real-time volgen van een opera over een telecomverbinding vanop afstand op een andere locatie dan waar de live uitvoering doorgaat.
- Het lezen van een boek in fysieke vorm, dan wel niet op een e-reader of online. 
- Het volgen van een event via een publiek scherm of internet connectie.
- Het opdelen van een cultuurevent in delen op een andere tijdsmoment.
- Het participeren aan een kunstroute al wandelend, dan wel al fietsend; met een gids of zonder.  
- Het afspelen van een film op meerdere mogelijke infrastructuren. 
- Een installatie van "eenzelfde" installatie in diverse locaties.

**Comment by jitsedc** [comment]
`Activiteit.doelgroep` en  `ParticipantProfiel.bepaaltBeperking` kunnen beide gebruikt worden om deel van deze use cases te realiseren. Verder werd ook `deelnamerecht` toegevoegd aan `Deelname` als ankerpunt om dit verder te kunnen uit te modelleren in een mogelijke volgende iteratie indien gewenst.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
