### ISSUE TITLE
foutieve URIs in AP

### ISSUE THREAD

**Issue by nvdk** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#18]
Er zijn een hele hoop URIs in het AP incorrect of onvolledig. Ik lijst ze hier op voor correctie door de editors:

## fixme urls voor
- De klasse Infrastructuur
- relatie infrastructuur op Activiteit
- relatie infrastructuur op Aanbieder
- relatie activiteit op de klasse Deelname
- relatie participant op klasse Deelname
- relatie identificator op klasse Ding
- attribuut beschikbaar op klasse Document
- de klasse FeedbackBron
- de klasse Nationaliteit
- het attribuut status op Organisatie (heeft ook geen label in het AP)
- relatie aanbieder(source) op klasse Samenwerking
- relatie aanbieder(target) op klasse Samenwerking
- relatie activiteit op klasse Uitvoering
- relatie uitvoerder op klasse Uitvoering
- 
## CIDOC base is niet correct:
* https://cidoc-crm.org/html/cidoc_crm_v7.1.1.html#E7 dit zou http://cidoc-crm.org/cidoc-crm/7.1.1/E7_Activity (of eventueel http://cidoc-crm.org/cidoc-crm/E7_Activity ) moeten zijn

**Comment by nvdk** [comment]
aanvullend: 
Op de klasse activiteit is voor het attribuut "identificator" de URI "https://www.w3.org/ns/adms#Identifier" gebruikt, maar dit moet https://www.w3.org/ns/adms#identifier zijn (kleine i, want relatie ipv klasse)

**Comment by jitsedc** [comment]
De URIs zouden correct moeten weergegeven zijn op de [testpublicatie](https://test.data.vlaanderen.be/doc/applicatieprofiel/doelgericht-digitaal-transformeren/ontwerpstandaard/2021-10-01#Infrastructuur) van de nieuwe versie van de specificatie: 
- [x] URI klasse `Infrastructuur`
- [x] relatie infrastructuur op `Activiteit`
- [x] relatie infrastructuur op Aanbieder
- [x] relatie activiteit op de klasse Deelname
- [x] relatie participant op klasse Deelname
- [x] relatie identificator op klasse Ding
- [x] attribuut beschikbaar op klasse Document
- [x] de klasse (enum) FeedbackBron
- [x] de klasse Nationaliteit
- [x] het attribuut status op Organisatie (heeft ook geen label in het AP)
- [x] relatie aanbieder(source) op klasse Samenwerking
- [x] relatie aanbieder(target) op klasse Samenwerking
- [x] relatie activiteit op klasse Uitvoering
- [x] relatie uitvoerder op klasse Uitvoering
- [x] cidoc-crm uri is ook gefixt
- [x] Identifier van W3C vervangen door URI identifier
