### ISSUE TITLE
Participanttype is niet gedefinieerd

### ISSUE THREAD

**Issue by nvdk** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#19]
Een [AlgemeenParticpantKenmerk](https://data.vlaanderen.be/ns/cultuurparticipatie#AlgemeenParticipantKenmerk) heeft een "Participanttype" als range voor het attribuut type. Maar deze klasse werd niet gedefinieerd.

**Comment by jitsedc** [comment]
Deze werd gedefinieerd als `skos:Concept`. Er werd een enumeratie toegevoegd met enkele voorbeelden om duidelijk te maken welke waarden hier zouden kunnen komen. Is dit duidelijk op deze manier?

![image](https://user-images.githubusercontent.com/93584054/188740638-247921d0-2035-4405-b1fe-74f1c67b4c1d.png)

**Comment by planetsizebrain** [comment]
@jitsedc dat kan dan wel betekenen dat iedereen de `skos:Concept` "enum"  anders invult? In de context van verschillende data producten die eenzelfde output entiteit hebben (met daarin 1 of meerdere `skos:Concept` velden) kan dit voor vreemde gevallen gaan zorgen als je dat soort data gaat aggregeren over meerdere data producten heen (bv in een data mesh). Moet je dan als data mesh bv zelf wel een invulling van de enum gaan voorzien die de data producten dan allemaal gaan moeten gebruiken zodat je zeker bent dat de enum waardes consistent en bruikbaar zijn of zijn er andere manieren?

**Comment by nvdk** [comment]
Dit lijkt op de test publicatie nog niet in orde: https://test.data.vlaanderen.be/doc/applicatieprofiel/doelgericht-digitaal-transformeren/ontwerpstandaard/2021-10-01#AlgemeenParticipantkenmerk . 
Het verwachte type zou hier skos:Concept moeten zijn? eventueel met opmerking/usageNode dat voorbeeld waarden in de enum participanttype kunnen worden gevonden? Alternatief: enums  ook in de documentatie opnemen, nu enkel zichtbaar in de uml afbeelding...

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
