### ISSUE TITLE
Voorbeeld van hoe een doelgroep wordt uitgedrukt is noodzakelijk

### ISSUE THREAD

**Issue by nvdk** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#20]
Het is op basis van het applicatieprofiel niet duidelijk hoe de doelgroep van een activiteit wordt uitgedrukt:
- als er geen specifieke doelgroep is, wordt er dan geen doelgroep op gegeven?
- stel de minimum leeftijd is 18j hoe wordt dit dan uitgedrukt? Is het volgende voorbeeld correct? 
```
{
     "@context": {
        "cultuurparticipatie": "https://data.vlaanderen.be/ns/cultuurparticipatie#",
        "schema": "http://schema.org/",
        "cidoc": "http://www.cidoc-crm.org/cidoc-crm/",
        "Activiteit": "cidoc:E7_Activity",
        "ParticipantProfiel": "cultuurparticipatie:ParticipantProfiel",
        "doelgroep": "https://data.vlaanderen.be/ns/cultuurparticipatie#Activiteit.doelgroep",
        "sociodemografisch": "https://data.vlaanderen.be/ns/cultuurparticipatie#ParticipantProfiel.sociodemografisch",
        "leeftijdsGroep": "schema:typicalAgeRange"
    },
    "@type": "Activiteit",
    "doelgroep": {
        "@type": "ParticipantProfiel",
        "sociodemografisch": {
          "leeftijdsGroep": "18-"
        }
    }
}
```

Gaat dit niet leiden tot het aanmaken van heel veel ad hoc participantprofielen?

**Comment by jitsedc** [comment]
We stellen voor om de relatie tussen `Activiteit` en `ParticipantProfiel` om te draaien. We denken dat dit de verwarring veroorzaakt waarop gedoeld wordt. 

![image](https://user-images.githubusercontent.com/93584054/188739386-4e8e489e-e88d-4cdf-8123-84945a49f81e.png)


We stellen ook voor om de waarde van `leeftijdsgroep` uitgebreider te modelleren als volgt: 
![image](https://user-images.githubusercontent.com/93584054/188739161-cbf1816b-3ca2-4115-925d-e484f6170ad5.png)

Het voorbeeld gegeven door Niels geeft aan dat dit voorstellen a.d.h.v. een simpele string niet voldoende is.

**Comment by nvdk** [comment]
De voornaamste bezorgdheid hier was eerder dat er geen gedeelde lijsten van particpant kenmerken zijn. Aangezien ze ook geen identifier moeten krijgen maakt dit het niet eenvoudig om met de data van verschillende publishers aan de slag te gaan.

E.g. stel dat ik een website wil maken op deze data die filters aanbiedt om te filteren op leeftijdsgroep. er is geen eenduidige manier om aan te duiden wanneer een evenement voor "iedereen" toegankelijk is. Betekent de afwezigheid van informatie dat er geen restricties zijn  of dat ze niet gedefinieerd zijn, hier zou enige guidance in de standaard gewenst zijn.

Mbt. uitbreiding leeftijdsgroep: persoonlijk vind ik de meerwaarde van het opsplitsen beperkt, de manier waarop schema.org ageRanges uitdrukt is courant en relatief makkelijk te parsen. beide lijken me een werkbare oplossing voor uitwisseling (intern zal de boven en ondergrens bijna altijd opgesplitst worden in eigen velden)

**Comment by jitsedc** [comment]
Voorstel om dus https://schema.org/typicalAgeRange te gebruiken met een string als verwachte waarde. Datatype `Leeftijdsgroep` werd verwijderd uit het model.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
