### ISSUE TITLE
groepsparticipatie

### ISSUE THREAD

**Issue by thomas-buijs** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#23]
Een participant kan deel uitmaken van een groep. Tickets kunnen op groepsniveau aangekocht worden door een vertegenwoordiger van de groep zonder dat verder iets gekend is over de eigenlijke participanten. Het model voorziet deze mogelijkheid niet.

**Comment by jitsedc** [comment]
De mogelijkheid wordt voorzien door `Transactie.aangekochtDoor`. Verder moet er buiten voor een `Deelname` geen informatie gegeven worden rond de `Participant`.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
