### ISSUE TITLE
Ontbrekende relatie prijsinfo

### ISSUE THREAD

**Issue by thomas-buijs** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#24]
De klasse prijsinfo staat momenteel totaal los van de transactie die hieruit volgt wat onlogisch lijkt.

**Comment by jitsedc** [comment]
De uiteindelijke prijs van de transactie wordt bepaald door `Transactie.prijs`. Automatische prijstoekenning zou nog steeds kunnen gebeuren aan de hand van de gekende info over de `Participant` en `Prijsinfo`. De prijsinfo is gelinkt via `Transactie`>`Deelname`>`Activiteit`>`Prijsinfo`. Het verder uitmodelleren hiervan lijkt niet nodig.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
