### ISSUE TITLE
Grondige review van klassen en attributen noodzakelijk

### ISSUE THREAD

**Issue by thomas-buijs** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#25]
Meerdere klassen en attributen hebben ongelukkige benamingen (bv. ticket i.p.v. het generiekere toegangsbewijs);
Meerdere attributen staan misplaatst binnen bepaalde klassen (bv. themaActiviteit bij klassen uitvoerder en aanbieder);
Meerdere attributen zijn momenteel duidelijk niet goed gedefinieerd, met onduidelijke of soms foutieve of dubbelzinnige codelijsten waardoor het onmogelijk is te controleren of het model eigenlijk wel goed zit (bv. Aabiedertype)

**Comment by jitsedc** [comment]
Toegansbewijs lijkt niet meteen generieker dan `Ticket`. Zo zou een `Ticket` een Toegangsbewijs kunnen zijn maar is een Toegangsbewijs niet automatisch een `Ticket`.
De attribuering rond `themaActiviteit` is bewust bij beide gezet om een indicatie te kunnen geven rond welke `thema`'s Uitvoerder en `Aanbieder`/Organisator werken.

**Comment by jitsedc** [comment]
Rond enumeraties is de [gerelateerde issue](https://github.com/Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren/issues/15) relevant. Op basis van Kunstendecreet en Cultureel erfgoed decreet werden deze eenduidiger gemaakt.
