### ISSUE TITLE
ContactInfo - kardinaliteit email, tel, url van 0..1 naar 0..*

### ISSUE THREAD

**Issue by Stiksels** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#26]
In UiTdatabank is het mogelijk om in de contactPoint meerdere entries in te voeren voor email, tel, website. Als we die in transformatie naar OSLO-contactInfo moeten reduceren tot 1, is er kans dat we belangrijke info verliezen

![188752087-d400d331-67bf-4031-8d8d-1546837701c4](https://user-images.githubusercontent.com/6908947/189045404-a135dac5-60ab-430d-8949-999419475f2e.png)

**Comment by jitsedc** [comment]
[Relevante issue](https://github.com/Informatievlaanderen/OSLOthema-Generiek/issues/9) binnen OSLO-Generiek
De workaround momenteel is dat de kardinaliteit voor het attribuut (niet het verwachte datatype) binnen het model op 0..* is gezet. Meerdere `ContactInfo`'s kunnen m.a.w. gegeven worden maar dan worden deze gezien als aparte objecten.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
