### ISSUE TITLE
Activiteit.tijd gebruikt datatype als URI (https://www.w3.org/2001/XMLSchema#dateTime)

### ISSUE THREAD

**Issue by nvdk** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#27]
Op dit moment wordt "https://www.w3.org/2001/XMLSchema#dateTime" gebruikt voor de eigenschap "tijd" op Activiteit, maar dit is een rdfs:Datatype en geen rdfs:Property. 

Voorstel: https://data.vlaanderen.be/ns/cultuurparticipatie#Activiteit.tijd gebruiken ?

**Comment by jitsedc** [comment]
URI werd aangepast naar [die van CIDOC-CRM voor Activity](http://cidoc-crm.org/cidoc-crm/7.1.2/P4_has_time-span)
