### ISSUE TITLE
Aanbieders hebben bepaalde velden die Uitvoerders niet hebben, en omgekeerd

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#3]
Bij Uitvoerder lijkt te ontbreken:
- identificator
- infrastructuur, bv. Rosas is een uitvoerder (dansgezelschap) en heeft een eigen infrastructuur in Vorst
- organisatievorm
- type

Bij Aanbieder lijkt dan te ontbreken:
- vermeldAls
- rol

Het lijkt me wenselijk om Aanbieder == Uitvoerder te houden aangezien de personen, collectieven of organisaties die een aanbiedende of uitvoerende rol opnemen zich niet laten vastzetten. Zo kan een programmator nu eens optreden als uitvoerder (bv. samensteller van concertprogramma, en neemt zo een artistieke rol op), dan wel ook zelf de concertorganisatie en -promotie opnemen (en is dan de aanbieder, vermoedelijk in samenwerking met een concertzaal).

Er is zelfs een argument te maken om ook Participanten helemaal gelijk te modelleren met Aanbieders en Uitvoerders, omdat bv. in participatieve kunsten die rollen ook makkelijk kunnen wijzigen.

**Comment by zvdh** [comment]
De hele opdeling in Aanbieder en Uitvoerder (met daaraan gekoppeld een Uitvoering) is niet steeds van toepassing binnen het sociaal-cultureel werk. 

Wordt de mogelijkheid voorzien om zowel Aanbieder als Uitvoerder aan dezelfde organisatie of persoon toe te wijzen? Of is het dan interessanter (en is dat dan ook mogelijk) om Uitvoerder (en Uitvoering) leeg te laten?

**Comment by jitsedc** [comment]
**Voor `Uitvoerder`**

- `identificator `toegevoegd aan `Uitvoerder`
- `infrastructuur` toegevoegd aan `Uitvoerder`
- `organisatievorm` toegevoegd aan `Uitvoerder`
- voor `type` lijkt mij het bestaande attribuut 'rol' reeds voldoende? Ik zou maar één van beide behouden voor `Uitvoerder`

**Voor `Aanbieder`/Organisator**

- `alternatieveNaam` reeds voorzien als attribuut, vangt dit niet vermeldAls voldoende op? 
- `rol` is reeds toegevoegd aan het nieuwe diagram

Aan de hand van double typing kan éénzelfde organisatie zowel `Aanbieder` als `Uitvoerder` zijn. Het is niet verplicht om één van beide in te vullen volgens de specificatie. Echter kunnen deze restricties wel opgelegd worden in implemenatie(modellen).

**Comment by ruettet** [comment]
alternatieve namen zijn aliassen: mauro pawlowski is ook bekend als mauro, somnabula, otot, ... Dat zou je inderdaad moeten kunnen modelleren, maar dat is een grote oefening.
in de context van een specifieke activiteit kan mauro pawloski kiezen voor één van de aliassen, of zelfs een nieuwe alias zien (dan is dat vermeld als, en dat is een attribuut van de relatie tussen de persoon en de activiteit, niet van de persoon zelf).

**Comment by jitsedc** [comment]
Oké, helder. 

Ik denk dat we dit kunnen oplossen door een attribuut `uitvoerderVermeldAls` toe te voegen aan de associatieklasse `Uitvoering` tussen `Activiteit` en `Uitvoerder`.

**Comment by ruettet** [comment]
en hoort dan "rol" ook niet daar in die associatieklasse? Die rol van de Uitvoerder is immers altijd afhankelijk van de Activiteit. Bij een concert met een band speel ik, afhankelijk van het concert en de anderen die kunnen meedoen, piano, bas of trombone. Ik kan dus drie rollen opnemen, en telkens een andere afhankelijk van de activiteit. Is dat al modelleerbaar?

**Comment by jitsedc** [comment]
Uitvoering.rol werd toegevoegd om hieraan tegemoet te komen. Bedankt!

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
