### ISSUE TITLE
property locatie op Activiteit heeft een verkeerde URI

### ISSUE THREAD

**Issue by nvdk** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#30]
Zie https://test.data.vlaanderen.be/doc/applicatieprofiel/doelgericht-digitaal-transformeren/ontwerpstandaard/2021-10-01/#Activiteit%3Alocatie

Deze suggereert https://www.w3.org/TR/2013/NOTE-prov-xml-20130430/#element-Location , maar dit is geen rdf:Property!
 Dit is een beschrijvende nota. Ik vermoed dat de bedoeling is om http://www.w3.org/ns/prov#atLocation te gebruiken (beschreven op https://www.w3.org/TR/prov-o/#atLocation).
Kan dit nog gecorrigeerd worden?

**Comment by jitsedc** [comment]
Aangepast naar de rdf:Property in plaats van de XML. Merci om dit te spotten.
