### ISSUE TITLE
consistent gebruik van cidoc namespace

### ISSUE THREAD

**Issue by nvdk** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#31]
Er worden nu verschillende namespaces gebruikt voor cidoc, het zou duidelijker zijn om er 1 consistent te gebruiken.
Voorbeeld:
- Activiteit krijgt als URI http://www.cidoc-crm.org/cidoc-crm/E7_Activity
- de eigenschap tijd van activiteit krijgt als URI http://cidoc-crm.org/cidoc-crm/7.1.2/P4_has_time-span

Consistent zou zijn voor beide de URI met versie of zonder versie te gebruiken

**Comment by jitsedc** [comment]
Bedankt om hierop te wijzen. Er is verkozen om de URI te nemen zonder versionering. Alle URIs zouden aangepast moeten zijn.
