### ISSUE TITLE
Link tussen Activiteit.label en Activiteit.labelType niet logisch

### ISSUE THREAD

**Issue by Stiksels** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#33]
https://data.vlaanderen.be/ns/cultuurparticipatie/#Activiteit.label = Te gebruiken om zaken die niet met andere codelijsten, datatypes, etc. worden ingevuld aan te vullen.

https://data.vlaanderen.be/ns/cultuurparticipatie/#Activiteit.labeltype = enum (publiek of verborgen)

Kardinaliteit van een label op een Activiteit = 0..*
Kardinaliteit van een labelType op een Activiteit = 0..*

Hoe kan je aangeven of een specifiek label verborgen is?

Logischer zou zijn dat labelType een eigenschap is op een Label?

**Comment by nvdk** [comment]
het lijkt me dan inderdaad logischer om een label en verborgenLabel als attributen toe te voegen.

**Comment by jitsedc** [comment]
Merci om dit te flaggen. Werd initieel toegevoegd omdat de vrees was dat enums niet voldoende zouden zijn voor bepaalde organisaties (of ze die niet wouden gebruiken) en ze zo eigen labels zouden kunnen toevoegen los van bv. Activiteittype etc. Zou inderdaad beter als datatype worden opgevat. Ik kijk even rond of we hier niet iets internationaal voor kunnen herbruiken. 

Staat voor mij los van het toevoegen van verborgenLabel toe te voegen. Dit is de simpele oplossing maar begrenst dan weer de mogelijkheid om andere type labels mee te geven indien gewenst zonder voor elk type label een nieuw attribuut op de klasse te moeten toevoegen.

**Comment by Stiksels** [comment]
@jitsedc heb je hier al iets rond gevonden? Dan zouden we op deze voorgestelde werkwijze al verder kunnen met onze implementatie

**Comment by jitsedc** [comment]
[Nu ook in productie beschikbaar](https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie/). Laat je me weten of dit voor jullie oké is? Dan sluit ik de issue.

**Comment by Stiksels** [comment]
@jitsedc dit werkt voor ons! Bedankt voor het voorstel en excuses voor het trage antwoord. Om de één of andere reden krijg ik geen meldingen binnen van deze github repo
