### ISSUE TITLE
SHACL template geeft validatie error: Shape with multiple sh:path predicates found

### ISSUE THREAD

**Issue by Stiksels** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#39]
De [shacl template  Cultuurparticipatie](https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie/erkendestandaard/2024-06-20/shacl/DoelgerichtDigitaalTransformeren-ap-SHACL.ttl) geeft een validatie error (bij gebruik van pyshacl library)

Ligt dit aan het dubbele gebruik van de `shacl:name "voert uit"@nl`  ?
https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie/#Realisator
![image](https://github.com/user-attachments/assets/1929d165-3425-4b11-8729-a87e8e0c0a88)

error:
```
Debugging SHACL shapes for errors...
Shape with multiple sh:path predicates found: https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie/erkendestandaard/2024-06-20#RealisatorShape/6fce063e03afed4078f32664201c46b0c53da61a
 - sh:path: https://data.vlaanderen.be/ns/cultuurparticipatie#Realisator.realiseert
 - sh:path: https://data.vlaanderen.be/ns/cultuurparticipatie#Realisator.voertUit
```

Meer info
```
<https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie/erkendestandaard/2024-06-20#RealisatorShape/6fce063e03afed4078f32664201c46b0c53da61a> rdfs:seeAlso "https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie/erkendestandaard/2024-06-20#Realisator.voertuit";
  shacl:class crm:E7_Activity,
    <https://data.vlaanderen.be/ns/cultuurparticipatie#Promotie>;
  shacl:description "De Realisator voert de Activiteit uit."@nl,
    "De Realisator die Promotie uitvoert."@nl;
  shacl:name "voert uit"@nl;
  shacl:path <https://data.vlaanderen.be/ns/cultuurparticipatie#Realisator.realiseert>,
    <https://data.vlaanderen.be/ns/cultuurparticipatie#Realisator.voertUit> .
```

**Comment by jitsedc** [comment]
Ik neem deze even op.

**Comment by jitsedc** [comment]
Ik heb het foutje gevonden. Een foutje in 1 label waardoor de mapping richting de SHACL verkeerd liep en hij die samenzette. Ik herpubliceer en zal link naar de juiste SHACL geven.

**Comment by jitsedc** [comment]
![image](https://github.com/user-attachments/assets/64bd1001-7c6c-49d1-80d9-1d9b9a186dbf)

@Stiksels zou moeten gefixt zijn. Probeer gerust nog eens en sluit de issue indien opgelost. Cheers!

[Link naar de nieuwe SHACL](https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie/erkendestandaard/2024-09-11/shacl/DoelgerichtDigitaalTransformeren-ap-SHACL.ttl)

Let op, de versie is nu https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie/erkendestandaard/2024-09-11 als je een bookmark zou hebben zet je die best op https://data.vlaanderen.be/doc/applicatieprofiel/cultuurparticipatie die verwijst automatisch door naar de laatste versie.

**Comment by Stiksels** [comment]
Hi @jitsedc deze is ok nu, bedankt! Ik sluit het issue
