### ISSUE TITLE
Associatietabel Aanbieder / Activiteit

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#4]
Parallel met de associatietabel Uitvoerder / Activiteit kan ook de relatie tussen een Aanbieder en een Activiteit genuanceerd zijn. Welke rol neemt de Aanbieder op? Op welke plaats wordt de Aanbieder gezet (misschien zelfs voor de Uitvoerder, hoe modelleer je dat?)? Welke rol neemt de Aanbieder op?

Bv. Nuff said als "brand" is vermoedelijk een uitvoerder (want ze maken artistieke keuzes) én een aanbieder (want ze organiseren het concert), maar doen dat bv. in samenwerking met De Warande. (https://nuffsaid.be/) De rol van Nuff Said is dan programmator of samensteller ofzo, de rol van De Warande is de presentatieplek. Concreet wordt in dit geval Nuff Said "groter geafficheerd" dan de namen die geprogrammeerd worden: https://www.warande.be/programma/5828/%27Nuff_Said/_Jade_Mintjens_Shakuar_Julie_Cafmeyer_Lucid_Lucia_Soe_Nsuki_en_Bas_Birker

**Comment by ruettet** [comment]
ook als "locatie" een aparte klasse zou zijn (maar dan hopelijk niet als aparte objecten in het data model, want dan krijg je "de warande" als aanbieder én als locatie, of "theater malpertuis" als locatie, aanbieder én uitvoerder; dat zou enorm veel vervuiling zijn... dat zijn gewoon allemaal actoren die bepaalde rollen opnemen) dan is typering nog zinvol. Bv. VIERNULVIER als "merk" voor de locatie WINTERCIRCUS, maar daarin een andere organisatie die iets organiseert, misschien in het kader van een festival: dat zijn vier "rollen".

**Comment by jitsedc** [comment]
De typering/rolverdeling van verschillende `Uitvoerders` en `Aanbieders`/Organisators is mogelijk met het model. De implicaties die dat kan hebben op vlak van affichering, betaling, etc. lijkt me hier out of scope. Aan de hand van de associatieklasse `Uitvoering` met attribuut `rang` kan er wel een rangschikking gemaakt worden voor specifieke `Activiteiten`.

`locatie` kan geen rol aangeschreven worden binnen het model en hangt steeds vast aan een bovenstaande klasse. De bevuiling die je beschrijft is dan niet echt van toepassing denk ik. Is je bezorgdheid hiermee beantwoord?

**Comment by ruettet** [comment]
ok, ik begrijp dan goed dat jullie de logica volgen zoals wikidata dat voorstelt: https://www.wikidata.org/wiki/Wikidata:WikiProject_Performing_arts/Data_structure/Data_modelling_issues

**Comment by jitsedc** [comment]
Dit is inderdaad dezelfde logica. Er wordt hier m.a.w. niet aan conflation gedaan.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
