### ISSUE TITLE
Samenwerking ook mogelijk tussen uitvoerders

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#5]
Er ontbreekt een samenwerkingstabel tussen uitvoerders, cf. bij Aanbieders. Bv. op het moment van schrijven is er een concert in de Hopper van Vaganée/Gerstmans/Verbruggen. Dat zijn drie aparte uitvoerders die voor deze gelegenheid samenwerken in een trio: https://www.cafehopper.be/

**Comment by jitsedc** [comment]
Terechte opmerking. Gezien Samenwerking een associatieklasse is, kan dit niet gedupliceerd worden tussen voor verschillende klassen. 

Voorstel om dit op een hoger niveau te tillen. Samenwerking komt dan op niveau van Agent zoals op het diagram hieronder:
<img width="217" alt="agentsamenwerking" src="https://user-images.githubusercontent.com/93584054/201448417-1c71a2f6-00fd-47b1-b2b0-894412b5306c.png">

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
