### ISSUE TITLE
Associatietabel Participant / Activiteit

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#6]
Het is nogal reducerend om participanten louter te zien als consumenten van een activiteit. In de participatieve kunsten nemen "participanten" specifiek een rol op. Vermoedelijk is dit ook zo bij sociaal-cultureel volwassenenwerk, erfgoed, ... Welke rol neemt de participant op? Is dat die van een workshopgever (of is dat dan een uitvoerder?), actieve deelhebber, passieve deelname, ....

Bovendien is een voorbeeld van een culturele activiteiten ook een kunstenaar die een residentie doet, bv. https://morphovzw.be/residenties/development-residency-2021 Zijn die kunstenaars dan participanten van het aanbod van de residentieplek? Moeten dan de participanten niet veel uitgebreider beschreven kunnen worden?

**Comment by zvdh** [comment]
Helemaal akkoord met Tom: binnen het sociaal-cultureel werk kan een participant heel veel verschillende rollen opnemen. 

Momenteel voorziet de tabel `DeelnameType` vier opties, nl. bezoeker, toeschouwer, actief en passief. Dit dekt de lading hoegenaamd niet. Ik neem aan dat deze lijst nog verder uit te breiden is? 
Is het aangewezen om deze lijst ook te koppelen aan het `ActiviteitType` van de activiteit (waarbij het gekozen `ActiviteitType` de mogelijkheden op gebied van `DeelnameType` beperkt)?

**Comment by jitsedc** [comment]
Die lijst is inderdaad louter illustratief en uitbreidbaar. 

Voorstel om deze zaken illustratief aan `DeelnameType`  toe te voegen. Indien attribuering van Participant voor uiterst betrokken `Participant` te kort schieten zou je ook met double typing kunnen werken en deze ook registreren als `Uitvoerder`. Alternatief zou er een attribuut `rol` kunnen toegevoegd worden aan de associatieklasse `Deelname` maar dan moet er goed onderscheid gemaakt worden tussen de semantische betekenis van `type` en `rol` binnen de klasse. 

@zvdh Het laatste puntje dat je aanhaalt lijkt me eerder iets voor implementaties.

**Comment by ruettet** [comment]
dat onderscheid tussen type, rol, functie, instrument, credit, ... is inderdaad heel belangrijk. Dit is echt cruciaal!

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
