### ISSUE TITLE
Samenwerkingen tussen Aanbieders / Uitvoerders

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#7]
Heel wat aanbieders en uitvoerders hebben (structurele) samenwerkingen, die nu niet gemodelleerd kunnen worden. Je zou kunnen zeggen dat De Vooruit een "aanbieder" is en de nieuwe organisatie VierNulVier de uitvoerder is (want ze maken een artistiek programma). Idem voor de Kopergietery in de Kazematten, of LOD op de Bijlokesite.

**Comment by jitsedc** [comment]
Laat ons dit samen met #5 behandelen.
