### ISSUE TITLE
Relaties tussen activiteiten moet getypeerd kunnen worden (associatietabel)

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#8]
Twee activiteiten kunnen nu met mekaar gelinkt worden via een sub/super relatie, maar er is geen typering mogelijk. Hoe geef je aan dat in een reeks van voorstellingen een bepaalde voorstelling gezien wordt als de première die geldt voor de taxshelter, en de andere voorstelling ervoor als try-out?

**Comment by ruettet** [comment]
Als je het helemaal doordenkt is de "hierarchie" eigenlijk ook maar een type van de relatie. Dus de vraag Thomas daarnet was wel relevant, in de zin dat je misschien de sub/super relatie kan "downgraden" naar gewoon een relatie tussen twee activiteiten? En dan is "super" of "sub" een type van relatie tussen de activiteiten. En dat geeft ruimte om ook een derde of vierde type te maken, die dan eerder lateraal zijn, bv. "is een preview van"?

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
