### ISSUE TITLE
Een Activiteit kan een eigen plaats hebben

### ISSUE THREAD

**Issue by ruettet** [Informatievlaanderen/OSLOthema-DoelgerichtDigitaalTransformeren#9]
Er is een veld Locatie bij Activiteit, maar het is onduidelijk wat er hier mee bedoeld wordt? Het zou goed zijn als een activiteit een eigen gemeente/land kan krijgen, omdat soms uitvoerder en aanbieders niet indicatief genoeg zijn voor de plek waar iets plaatsvindt.

**Comment by ruettet** [comment]
ok, dus locatie is zowel een "culturele infrastructuur", een gps punt, een adres, ...?

**Comment by jitsedc** [comment]
Voor infrastructuur is de link met OSLO-C&JI voorzien. Maar kan inderdaad in de zeer ruime zin worden geïnterpreteerd zodat onder andere ook online evenementen een locatie kunnen hebben.

**Comment by ruettet** [comment]
dus als een cc Dat CC een concert van Die Band organiseert op een pleintje in Andere Gemeente, dan:
- linkt activiteit naar de Organisator "Dat CC"
- linkt activiteit naar de Uitvoerder "Die Band"
- linkt activiteit naar de Locatie "Dat CC"
- maar is in het veld Locatie van die Activiteit de naam van Andere Gemeente opgenomen? Waarbij dan een gemeente ook een entiteit is bij Locaties? Of een specifiek pleintje in die gemeente wordt misschien beschreven door een polygoon? Of is dat pleintje een Culturele Infrastructuur?

**Comment by jitsedc** [comment]
Affirmatief, wel met de nuance dat voor 'Dat CC' een onderscheid wordt gemaakt tussen de organisatie 'Dat CC' en de `Locatie` waar 'Dat CC' zich bevindt. 

Veld `Locatie`: beide opties zijn mogelijk bij het generieke `Locatie`, afhankelijk van de beschikbare granulariteit van de data.

**Comment by jitsedc** [comment]
Behandeld en goedgekeurd op de 6de en bijkomende werkgroep van 06/02/2023. Voor meer informatie zie het verslag van de werkgroep.
